package com.RPS.dao;

import com.RPS.model.ResumeDto;
import com.RPS.model.ResumeDtoExample;
import com.RPS.model.ResumeDtoWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ResumeDtoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int countByExample(ResumeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int deleteByExample(ResumeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int insert(ResumeDtoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int insertSelective(ResumeDtoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    List<ResumeDtoWithBLOBs> selectByExampleWithBLOBs(ResumeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    List<ResumeDto> selectByExample(ResumeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    ResumeDtoWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int updateByExampleSelective(@Param("record") ResumeDtoWithBLOBs record, @Param("example") ResumeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") ResumeDtoWithBLOBs record, @Param("example") ResumeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int updateByExample(@Param("record") ResumeDto record, @Param("example") ResumeDtoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int updateByPrimaryKeySelective(ResumeDtoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(ResumeDtoWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    int updateByPrimaryKey(ResumeDto record);
}