package com.RPS.model;

public class EnterpriseDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.id
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_name
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String enterpriseName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_address
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String enterpriseAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_phone
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String enterprisePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_person
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String enterprisePerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_industry
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String enterpriseIndustry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_scale
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String enterpriseScale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.username
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.enterprise_introduce
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String enterpriseIntroduce;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.id
     *
     * @return the value of enterprise.id
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.id
     *
     * @param id the value for enterprise.id
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_name
     *
     * @return the value of enterprise.enterprise_name
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getEnterpriseName() {
        return enterpriseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_name
     *
     * @param enterpriseName the value for enterprise.enterprise_name
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setEnterpriseName(String enterpriseName) {
        this.enterpriseName = enterpriseName == null ? null : enterpriseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_address
     *
     * @return the value of enterprise.enterprise_address
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getEnterpriseAddress() {
        return enterpriseAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_address
     *
     * @param enterpriseAddress the value for enterprise.enterprise_address
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setEnterpriseAddress(String enterpriseAddress) {
        this.enterpriseAddress = enterpriseAddress == null ? null : enterpriseAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_phone
     *
     * @return the value of enterprise.enterprise_phone
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getEnterprisePhone() {
        return enterprisePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_phone
     *
     * @param enterprisePhone the value for enterprise.enterprise_phone
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setEnterprisePhone(String enterprisePhone) {
        this.enterprisePhone = enterprisePhone == null ? null : enterprisePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_person
     *
     * @return the value of enterprise.enterprise_person
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getEnterprisePerson() {
        return enterprisePerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_person
     *
     * @param enterprisePerson the value for enterprise.enterprise_person
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setEnterprisePerson(String enterprisePerson) {
        this.enterprisePerson = enterprisePerson == null ? null : enterprisePerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_industry
     *
     * @return the value of enterprise.enterprise_industry
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getEnterpriseIndustry() {
        return enterpriseIndustry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_industry
     *
     * @param enterpriseIndustry the value for enterprise.enterprise_industry
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setEnterpriseIndustry(String enterpriseIndustry) {
        this.enterpriseIndustry = enterpriseIndustry == null ? null : enterpriseIndustry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_scale
     *
     * @return the value of enterprise.enterprise_scale
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getEnterpriseScale() {
        return enterpriseScale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_scale
     *
     * @param enterpriseScale the value for enterprise.enterprise_scale
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setEnterpriseScale(String enterpriseScale) {
        this.enterpriseScale = enterpriseScale == null ? null : enterpriseScale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.username
     *
     * @return the value of enterprise.username
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.username
     *
     * @param username the value for enterprise.username
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.enterprise_introduce
     *
     * @return the value of enterprise.enterprise_introduce
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getEnterpriseIntroduce() {
        return enterpriseIntroduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.enterprise_introduce
     *
     * @param enterpriseIntroduce the value for enterprise.enterprise_introduce
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setEnterpriseIntroduce(String enterpriseIntroduce) {
        this.enterpriseIntroduce = enterpriseIntroduce == null ? null : enterpriseIntroduce.trim();
    }
}