package com.RPS.model;

public class PersonalDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.id
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.head_img_url
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String headImgUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.real_name
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.sex
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.age
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.tel_no
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String telNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column personal.username
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    private String username;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.id
     *
     * @return the value of personal.id
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.id
     *
     * @param id the value for personal.id
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.head_img_url
     *
     * @return the value of personal.head_img_url
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getHeadImgUrl() {
        return headImgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.head_img_url
     *
     * @param headImgUrl the value for personal.head_img_url
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl == null ? null : headImgUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.real_name
     *
     * @return the value of personal.real_name
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.real_name
     *
     * @param realName the value for personal.real_name
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.sex
     *
     * @return the value of personal.sex
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.sex
     *
     * @param sex the value for personal.sex
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.age
     *
     * @return the value of personal.age
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.age
     *
     * @param age the value for personal.age
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.tel_no
     *
     * @return the value of personal.tel_no
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getTelNo() {
        return telNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.tel_no
     *
     * @param telNo the value for personal.tel_no
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setTelNo(String telNo) {
        this.telNo = telNo == null ? null : telNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column personal.username
     *
     * @return the value of personal.username
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column personal.username
     *
     * @param username the value for personal.username
     *
     * @mbggenerated Wed Apr 27 21:55:11 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }
}