package com.RPS.model;

public class ResumeDto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.id
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.education
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.username
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.is_show
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    private Boolean isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.is_pass
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    private Integer isPass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume.resume_img
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    private String resumeImg;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.id
     *
     * @return the value of resume.id
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.id
     *
     * @param id the value for resume.id
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.education
     *
     * @return the value of resume.education
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.education
     *
     * @param education the value for resume.education
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.username
     *
     * @return the value of resume.username
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.username
     *
     * @param username the value for resume.username
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.is_show
     *
     * @return the value of resume.is_show
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public Boolean getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.is_show
     *
     * @param isShow the value for resume.is_show
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public void setIsShow(Boolean isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.is_pass
     *
     * @return the value of resume.is_pass
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public Integer getIsPass() {
        return isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.is_pass
     *
     * @param isPass the value for resume.is_pass
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public void setIsPass(Integer isPass) {
        this.isPass = isPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume.resume_img
     *
     * @return the value of resume.resume_img
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public String getResumeImg() {
        return resumeImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume.resume_img
     *
     * @param resumeImg the value for resume.resume_img
     *
     * @mbggenerated Fri Apr 29 12:39:02 CST 2016
     */
    public void setResumeImg(String resumeImg) {
        this.resumeImg = resumeImg == null ? null : resumeImg.trim();
    }
}